import { Product, Category } from '../types';

// Mock data for development — replace with Firebase data in production
export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Skincare',
    description: 'Premium creams, serums, face washes & moisturizers formulated for healthy, glowing skin.',
    image: '',
    localImage: require('../assets/category-skincare.png'),
    productCount: 5,
    isActive: true,
    order: 1,
    color: '#2d7a52',
  },
  {
    id: 'cat-2',
    name: 'Hair Care',
    description: 'Shampoos, conditioners, and hair treatments for strong, beautiful hair.',
    image: '',
    localImage: require('../assets/category-haircare.png'),
    productCount: 0,
    isActive: true,
    order: 2,
    color: '#1a5c3a',
  },
  {
    id: 'cat-3',
    name: 'Personal Care',
    description: 'Body washes, soaps, and personal hygiene products for daily wellness.',
    image: '',
    localImage: require('../assets/category-personalcare.png'),
    productCount: 1,
    isActive: true,
    order: 3,
    color: '#7aaa8a',
  },
  {
    id: 'cat-4',
    name: 'Wellness',
    description: 'Supplements and health support products for a balanced, healthy lifestyle.',
    image: '',
    localImage: require('../assets/category-wellness.png'),
    productCount: 0,
    isActive: true,
    order: 4,
    color: '#b8976a',
  },
  {
    id: 'cat-5',
    name: 'Healthcare',
    description: 'Pharmaceutical and medical-grade products backed by clinical standards.',
    image: '',
    localImage: require('../assets/category-healthcare.png'),
    productCount: 0,
    isActive: true,
    order: 5,
    color: '#0d3d26',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-9',
    name: 'Facecure Cream',
    description: 'Facecure Cream is an advanced dermatological triple-action formulation featuring Hydroquinone, Tretinoin, and Mometasone Furoate. Scientifically designed to treat hyperpigmentation, melasma, dark spots, blemishes, and uneven skin tone for clear and healthy skin.',
    shortDescription: 'Triple-action formula with Hydroquinone, Tretinoin & Mometasone',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-facecure-cream.png'),
    benefits: [
      'Clinically proven triple-action skin brightening formula',
      'Visibly reduces melasma, hyperpigmentation & sun spots',
      'Encourages cellular skin renewal & refines skin texture',
      'Anti-inflammatory action minimizes redness & irritation',
      'Restores even skin tone and luminous clarity',
    ],
    activeIngredients: ['Hydroquinone USP 2.0%', 'Tretinoin USP 0.025%', 'Mometasone Furoate IP 0.1%'],
    ingredients: ['Hydroquinone USP 2.0% w/w', 'Tretinoin USP 0.025% w/w', 'Mometasone Furoate IP 0.1% w/w', 'Cream Base q.s.'],
    usage: 'Apply a thin layer once daily at night to the affected skin areas after washing. Use SPF sunscreen protection during daytime hours.',
    precautions: 'For external use only. Avoid contact with eyes, lips, and open cuts. Do not use during pregnancy. Limit exposure to sunlight.',
    packaging: '15g Tube',
    additionalInfo: 'Pharmaceutical grade dermatological formulation. Store below 25°C away from direct sunlight.',
    isActive: true,
    isFeatured: true,
    tags: ['cream', 'facecure', 'skincare', 'hyperpigmentation', 'melasma', 'tretinoin', 'clear skin'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-10',
    name: 'Facecure Herbal Soap',
    description: 'Facecure Herbal Soap is a therapeutic grade herbal antiseptic bathing bar enriched with pure Aloe Vera, Neem, and Tulsi. Specially formulated to purify, cleanse, and protect skin against acne-causing bacteria while preserving natural moisture and pH balance.',
    shortDescription: 'Herbal antiseptic bar enriched with Aloe Vera, Neem & Tulsi',
    categoryId: 'cat-3',
    categoryName: 'Personal Care',
    images: [],
    localImage: require('../assets/product-facecure-herbal-soap.png'),
    benefits: [
      'Natural 100% herbal formulation, chemical-free',
      'Antibacterial & antiseptic shield from Neem & Tulsi',
      'Prevents acne, breakouts, and skin impurities',
      'Deep cleansing while maintaining natural hydration',
      'Gentle on skin for daily face and body wellness',
    ],
    activeIngredients: ['Aloe Vera', 'Neem Oil', 'Tulsi Extract'],
    ingredients: ['Aloe Vera Extract', 'Neem Oil (Azadirachta Indica)', 'Tulsi Extract (Ocimum Sanctum)', 'Pure Glycerin', 'Grade-1 Soap Base'],
    usage: 'Work into a rich lather with water. Apply generously to wet face and body, leave on for 1-2 minutes, then rinse thoroughly.',
    precautions: 'For external use only. Avoid direct eye contact. Rinse immediately with cold water if contact occurs.',
    packaging: '75g Bar',
    additionalInfo: 'Grade-1 TFM soap base. Free from harsh chemicals and parabens, cruelty-free.',
    isActive: true,
    isFeatured: true,
    tags: ['soap', 'facecure', 'herbal', 'personal care', 'neem', 'aloe vera', 'tulsi', 'antibacterial', 'clean skin'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-11',
    name: 'Facecure Glow Shine Cream',
    description: 'Facecure Glow Shine Cream is an intensive brightening and radiance cream formulated with Glycolic Acid, Alpha Arbutin, Kojic Acid, Niacinamide, and broad-spectrum SPF 30. Formulated for both men and women to restore natural luminescence, fade dullness, and shield against UV damage.',
    shortDescription: 'Skin brightening cream for men & women with built-in SPF 30',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-glowshine-cream.png'),
    benefits: [
      'Synergistic brightening action with Arbutin, Kojic Acid & Niacinamide',
      'Gentle cell exfoliation and smoothing with Glycolic Acid',
      'Built-in broad-spectrum SPF 30 defends against photoaging & sun spots',
      'Imparts an instant radiant glow without grease or white cast',
      'Dermatologist tested formulation suitable for men and women',
    ],
    activeIngredients: ['Glycolic Acid', 'Alpha Arbutin', 'Kojic Acid', 'Niacinamide', 'SPF 30 Sun Protection Formula'],
    ingredients: ['Glycolic Acid', 'Alpha Arbutin', 'Kojic Acid Dipalmitate', 'Niacinamide (Vitamin B3)', 'SPF 30 UV Filters', 'Vitamin E Acetate', 'Hyaluronic Acid', 'Light Cream Base'],
    usage: 'Apply a pea-sized amount evenly over cleansed face and neck in the morning. Gently massage until fully absorbed.',
    precautions: 'For external use only. Conduct a patch test on forearm before first application. Avoid direct contact with eyes.',
    packaging: '20g Jar',
    additionalInfo: 'Non-comedogenic, dermatologically tested, suited for daily morning regimen.',
    isActive: true,
    isFeatured: true,
    tags: ['glow', 'shine', 'cream', 'facecure', 'skincare', 'brightening', 'kojic acid', 'niacinamide', 'spf30'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-12',
    name: 'Facecure Facewash',
    description: 'Facecure Facewash is a purifying herbal anti-acne face wash powered by pure Neem, Aloe Vera, Tea Tree Oil, and Tulsi extract. Formulated for all skin types, it delivers deep pore cleansing, reduces pimples, washes away excess oil, and leaves skin revitalized and clear.',
    shortDescription: 'Deep cleansing herbal facewash with Neem, Aloe Vera & Tea Tree Oil',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-facecure-facewash.png'),
    benefits: [
      'Helps visibly reduce acne and pimples within 15 days',
      'Deeply cleanses congested pores and extracts surface pollutants',
      'Antibacterial protection with pure Tea Tree Oil & Neem',
      'Soothes skin inflammation with Aloe Vera and Tulsi',
      '100% herbal active ingredients, safe for all skin types',
    ],
    activeIngredients: ['Neem', 'Aloe Vera', 'Tea Tree Oil', 'Tulsi Extract'],
    ingredients: ['Neem Extract (Azadirachta Indica)', 'Aloe Vera Barbadensis Gel', 'Tea Tree Oil (Melaleuca Alternifolia)', 'Tulsi Extract (Ocimum Sanctum)', 'Purified Water Base', 'Gentle Foaming Surfactants'],
    usage: 'Wet face and neck. Squeeze a small amount of Facecure Facewash onto palms and work into a lather. Gently massage in upward circular motions, then rinse thoroughly and pat dry. Use morning and night.',
    precautions: 'For external use only. Avoid direct contact with eyes. If contact occurs, rinse immediately with clean water.',
    packaging: '100ml Tube',
    additionalInfo: '100% herbal actives. Dermatologically tested. Non-drying deep cleansing formula.',
    isActive: true,
    isFeatured: true,
    tags: ['facewash', 'facecure', 'skincare', 'neem', 'tea tree oil', 'aloe vera', 'tulsi', 'acne', 'cleanser'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-13',
    name: 'Facecure Advance Gel',
    description: 'Facecure Advance Gel (Clindamycin & Nicotinamide Gel) is a targeted dermatological anti-acne medication. Combining antibacterial Clindamycin with anti-inflammatory Nicotinamide, it eradicates acne-causing bacteria, calms swelling and redness, and accelerates blemish healing.',
    shortDescription: 'Targeted anti-acne gel with Clindamycin & Nicotinamide',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-facecure-advance-gel.png'),
    benefits: [
      'Directly eliminates acne-causing bacteria (P. acnes)',
      'Relieves inflammatory acne lesions, swelling, and redness',
      'Regulates excess sebum production and prevents new comedones',
      'Fast-absorbing aqueous gel base that leaves no oily residue',
      'Dermatologist trusted formulation for clear, healthy skin',
    ],
    activeIngredients: ['Clindamycin Phosphate IP 1.0% w/w', 'Nicotinamide IP 4.0% w/w'],
    ingredients: ['Clindamycin Phosphate IP 1.0% w/w', 'Nicotinamide IP 4.0% w/w', 'Aqueous Gel Base q.s.'],
    usage: 'Cleanse the affected area with a gentle cleanser and pat dry. Apply a thin film of Facecure Advance Gel once or twice daily or as directed by your physician.',
    precautions: 'For external dermatological use only. Avoid contact with eyes, eyelids, mouth, and mucous membranes. Discontinue if extreme dryness or irritation develops.',
    packaging: '20g Tube',
    additionalInfo: 'Pharmaceutical grade topical formulation. Manufactured under certified GMP standards.',
    isActive: true,
    isFeatured: true,
    tags: ['gel', 'facecure', 'cream', 'skincare', 'clindamycin', 'nicotinamide', 'acne', 'advance gel'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-14',
    name: 'Facecure Skin Radiance Combo',
    description: 'Facecure Skin Radiance Combo is a comprehensive daily skincare synergy pairing Facecure Herbal Soap (Aloe Vera, Neem & Tulsi) and Facecure Glow Shine Cream (SPF 30, Glycolic Acid, Arbutin & Niacinamide). Purify, nourish, and shield your skin for all-day luminous glow.',
    shortDescription: 'Daily glow pack: Facecure Herbal Soap + Glow Shine Cream SPF 30',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/promo-enhance-skin.png'),
    benefits: [
      'Complete 2-step daily routine: cleanse and brighten',
      'Deep purification with natural Neem, Aloe Vera & Tulsi',
      'Targeted skin radiance with Glycolic Acid, Arbutin & Kojic Acid',
      'Broad-spectrum SPF 30 UV defense for daytime protection',
      'Specially bundled value combo for men and women',
    ],
    activeIngredients: ['Aloe Vera', 'Neem', 'Tulsi', 'Glycolic Acid', 'Arbutin', 'Kojic Acid', 'Niacinamide', 'SPF 30'],
    ingredients: ['Facecure Herbal Soap (75g)', 'Facecure Glow Shine Cream (20g)'],
    usage: 'Step 1: Cleanse face and neck with Facecure Herbal Soap and rinse with water. Step 2: Apply Facecure Glow Shine Cream evenly every morning.',
    precautions: 'For external use only. Patch test recommended before first use.',
    packaging: 'Combo Pack (Soap 75g + Cream 20g)',
    additionalInfo: 'Complete dual-action skin enhancement regimen.',
    isActive: true,
    isFeatured: true,
    tags: ['combo', 'kit', 'facecure', 'skincare', 'glow', 'soap', 'cream', 'spf30', 'radiance'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
