import { Product, Category } from '../types';

// Mock data for development — replace with Firebase data in production
export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Skincare',
    description: 'Premium creams, serums, face washes & moisturizers formulated for healthy, glowing skin.',
    image: '',
    productCount: 12,
    isActive: true,
    order: 1,
    color: '#2d7a52',
  },
  {
    id: 'cat-2',
    name: 'Hair Care',
    description: 'Shampoos, conditioners, and hair treatments for strong, beautiful hair.',
    image: '',
    productCount: 8,
    isActive: true,
    order: 2,
    color: '#1a5c3a',
  },
  {
    id: 'cat-3',
    name: 'Personal Care',
    description: 'Body washes, soaps, and personal hygiene products for daily wellness.',
    image: '',
    productCount: 10,
    isActive: true,
    order: 3,
    color: '#7aaa8a',
  },
  {
    id: 'cat-4',
    name: 'Wellness',
    description: 'Supplements and health support products for a balanced, healthy lifestyle.',
    image: '',
    productCount: 6,
    isActive: true,
    order: 4,
    color: '#b8976a',
  },
  {
    id: 'cat-5',
    name: 'Healthcare',
    description: 'Pharmaceutical and medical-grade products backed by clinical standards.',
    image: '',
    productCount: 9,
    isActive: true,
    order: 5,
    color: '#0d3d26',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Advanced Moisturizing Cream',
    description: 'A deeply nourishing moisturizing cream crafted with a blend of premium ingredients to restore and maintain optimal skin hydration. Suitable for all skin types.',
    shortDescription: 'Deep nourishment for all skin types',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    benefits: [
      'Deep hydration for up to 24 hours',
      'Restores skin barrier function',
      'Improves skin elasticity',
      'Non-greasy, fast-absorbing formula',
      'Suitable for sensitive skin',
    ],
    ingredients: ['Aqua', 'Glycerin', 'Shea Butter', 'Vitamin E', 'Niacinamide', 'Hyaluronic Acid'],
    usage: 'Apply a small amount to cleansed skin. Gently massage in circular motions until fully absorbed. Use twice daily, morning and night.',
    precautions: 'For external use only. Avoid contact with eyes. Discontinue use if irritation occurs. Keep out of reach of children. Store in a cool, dry place.',
    packaging: 'Available in 50g and 100g tubes',
    additionalInfo: 'Dermatologically tested. Free from harmful parabens and sulfates.',
    isActive: true,
    isFeatured: true,
    tags: ['moisturizer', 'skincare', 'hydration'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Gentle Foaming Face Wash',
    description: 'A gentle, pH-balanced foaming face wash that effectively removes impurities, excess oil, and makeup while maintaining the skin\'s natural moisture balance.',
    shortDescription: 'pH-balanced cleansing for daily use',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    benefits: [
      'Gently removes dirt and impurities',
      'Maintains natural skin pH',
      'Reduces excess oil without over-drying',
      'Leaves skin fresh and clean',
    ],
    ingredients: ['Aqua', 'Cocamidopropyl Betaine', 'Aloe Vera Extract', 'Green Tea Extract', 'Salicylic Acid'],
    usage: 'Wet face with lukewarm water. Apply a small amount and lather gently. Rinse thoroughly. Use morning and evening.',
    precautions: 'Avoid contact with eyes. If contact occurs, rinse immediately with water. For external use only.',
    packaging: '100ml pump bottle',
    additionalInfo: 'Suitable for oily to combination skin. Paraben-free.',
    isActive: true,
    isFeatured: true,
    tags: ['face wash', 'cleanser', 'skincare'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Nourishing Hair Shampoo',
    description: 'A professional-grade nourishing shampoo enriched with natural extracts that strengthens hair from root to tip, reducing breakage and adding incredible shine.',
    shortDescription: 'Strengthening formula for healthy hair',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    images: [],
    benefits: [
      'Strengthens hair from root to tip',
      'Reduces breakage and hair fall',
      'Adds natural shine and volume',
      'Nourishes dry and damaged hair',
    ],
    ingredients: ['Aqua', 'Sodium Laureth Sulfate', 'Argan Oil', 'Keratin', 'Biotin', 'Vitamin B5'],
    usage: 'Apply to wet hair, lather, and rinse. Repeat if necessary. Follow with conditioner for best results.',
    precautions: 'Avoid contact with eyes. For external use only. Keep out of reach of children.',
    packaging: '200ml bottle',
    additionalInfo: 'Free from harsh sulfates. Safe for color-treated hair.',
    isActive: true,
    isFeatured: false,
    tags: ['shampoo', 'hair care', 'nourishing'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Premium Bathing Soap',
    description: 'A luxurious bathing soap enriched with moisturizing agents and natural fragrances for a refreshing bathing experience that leaves skin soft and smooth.',
    shortDescription: 'Luxurious daily bathing soap',
    categoryId: 'cat-3',
    categoryName: 'Personal Care',
    images: [],
    benefits: [
      'Deep cleanses without stripping moisture',
      'Leaves skin soft and smooth',
      'Long-lasting fragrance',
      'Gentle formula suitable for all skin types',
    ],
    ingredients: ['Sodium Palmate', 'Sodium Palm Kernelate', 'Glycerin', 'Rose Extract', 'Vitamin E'],
    usage: 'Use daily during bath or shower. Lather and apply to wet skin. Rinse thoroughly.',
    precautions: 'For external use only. Avoid contact with eyes.',
    packaging: '100g bar',
    additionalInfo: 'pH balanced formula.',
    isActive: true,
    isFeatured: true,
    tags: ['soap', 'bathing', 'personal care'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Vitamin C Brightening Serum',
    description: 'A high-potency vitamin C serum that visibly brightens skin, reduces dark spots, and evens out skin tone for a radiant, youthful complexion.',
    shortDescription: 'Brighten and even out skin tone',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    benefits: [
      'Visibly brightens dull skin',
      'Reduces appearance of dark spots',
      'Evens out skin tone',
      'Antioxidant protection',
      'Boosts collagen production',
    ],
    ingredients: ['Ascorbic Acid (Vitamin C)', 'Niacinamide', 'Hyaluronic Acid', 'Ferulic Acid', 'Vitamin E'],
    usage: 'Apply 3-4 drops to cleansed face and neck. Pat gently until absorbed. Follow with moisturizer. Use morning and evening.',
    precautions: 'May cause temporary tingling on first use. Perform patch test before use. Avoid contact with eyes. Use SPF during the day.',
    packaging: '30ml dropper bottle',
    additionalInfo: 'Stabilized formula for maximum efficacy. Store in a cool, dark place.',
    isActive: true,
    isFeatured: true,
    tags: ['serum', 'vitamin c', 'brightening', 'skincare'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Herbal Wellness Lotion',
    description: 'A therapeutic body lotion crafted with herbal extracts and essential nutrients to promote skin wellness and overall body health.',
    shortDescription: 'Herbal body wellness formula',
    categoryId: 'cat-4',
    categoryName: 'Wellness',
    images: [],
    benefits: [
      'Nourishes and protects skin',
      'Natural herbal extracts',
      'Long-lasting moisture',
      'Promotes skin wellness',
    ],
    ingredients: ['Aqua', 'Shea Butter', 'Aloe Vera', 'Neem Extract', 'Turmeric Extract', 'Vitamin A'],
    usage: 'Apply to clean skin. Massage gently in upward circular motions until absorbed. Use twice daily.',
    precautions: 'For external use only. Avoid contact with eyes. Discontinue if irritation occurs.',
    packaging: '200ml pump bottle',
    additionalInfo: 'Made with natural herbal ingredients.',
    isActive: true,
    isFeatured: false,
    tags: ['lotion', 'herbal', 'wellness', 'body care'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Anti-Dandruff Hair Conditioner',
    description: 'A specially formulated conditioner that deeply conditions hair while targeting dandruff at its source, leaving hair soft, manageable, and scalp healthy.',
    shortDescription: 'Conditioning + dandruff control',
    categoryId: 'cat-2',
    categoryName: 'Hair Care',
    images: [],
    benefits: [
      'Controls dandruff effectively',
      'Deep conditioning for soft hair',
      'Reduces scalp irritation',
      'Adds natural shine',
    ],
    ingredients: ['Aqua', 'Cetearyl Alcohol', 'Zinc Pyrithione', 'Tea Tree Oil', 'Coconut Oil', 'Panthenol'],
    usage: 'After shampooing, apply to hair. Leave for 2-3 minutes. Rinse thoroughly.',
    precautions: 'Avoid contact with eyes. For external use only.',
    packaging: '200ml bottle',
    additionalInfo: 'Dermatologically tested for scalp health.',
    isActive: true,
    isFeatured: false,
    tags: ['conditioner', 'anti-dandruff', 'hair care'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    name: 'Sunscreen SPF 50+',
    description: 'Broad-spectrum UVA/UVB sunscreen with SPF 50+ protection that shields skin from sun damage while keeping skin moisturized and comfortable.',
    shortDescription: 'Broad-spectrum sun protection',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    benefits: [
      'Broad spectrum UVA/UVB protection',
      'SPF 50+ high protection',
      'Non-greasy, lightweight formula',
      'Water-resistant formula',
      'Suitable for daily use',
    ],
    ingredients: ['Zinc Oxide', 'Titanium Dioxide', 'Octinoxate', 'Avobenzone', 'Vitamin E', 'Hyaluronic Acid'],
    usage: 'Apply generously 15 minutes before sun exposure. Reapply every 2 hours or after swimming/sweating.',
    precautions: 'For external use only. Avoid contact with eyes. In case of contact, rinse well with water.',
    packaging: '60ml tube',
    additionalInfo: 'Tested under dermatological supervision. Safe for daily use.',
    isActive: true,
    isFeatured: true,
    tags: ['sunscreen', 'spf', 'sun protection', 'skincare'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-9',
    name: 'Facecure Cream',
    description: 'Facecure Cream is an advanced dermatological triple-action formulation featuring Hydroquinone, Tretinoin, and Mometasone Furoate. Scientifically designed to treat hyperpigmentation, melasma, dark spots, blemishes, and uneven skin tone for clear and healthy skin.',
    shortDescription: 'Triple-action formula with Hydroquinone, Tretinoin & Mometasone',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-facecure-cream.png'),
    benefits: [
      'Clinically proven triple-action skin brightening formula',
      'Visibly reduces melasma, hyperpigmentation & sun spots',
      'Encourages cellular skin renewal & refines skin texture',
      'Anti-inflammatory action minimizes redness & irritation',
      'Restores even skin tone and luminous clarity',
    ],
    activeIngredients: ['Hydroquinone USP 2.0%', 'Tretinoin USP 0.025%', 'Mometasone Furoate IP 0.1%'],
    ingredients: ['Hydroquinone USP 2.0% w/w', 'Tretinoin USP 0.025% w/w', 'Mometasone Furoate IP 0.1% w/w', 'Cream Base q.s.'],
    usage: 'Apply a thin layer once daily at night to the affected skin areas after washing. Use SPF sunscreen protection during daytime hours.',
    precautions: 'For external use only. Avoid contact with eyes, lips, and open cuts. Do not use during pregnancy. Limit exposure to sunlight.',
    packaging: '15g Tube',
    additionalInfo: 'Pharmaceutical grade dermatological formulation. Store below 25°C away from direct sunlight.',
    isActive: true,
    isFeatured: true,
    tags: ['cream', 'facecure', 'skincare', 'hyperpigmentation', 'melasma', 'tretinoin', 'clear skin'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-10',
    name: 'Facecure Herbal Soap',
    description: 'Facecure Herbal Soap is a therapeutic grade herbal antiseptic bathing bar enriched with pure Aloe Vera, Neem, and Tulsi. Specially formulated to purify, cleanse, and protect skin against acne-causing bacteria while preserving natural moisture and pH balance.',
    shortDescription: 'Herbal antiseptic bar enriched with Aloe Vera, Neem & Tulsi',
    categoryId: 'cat-3',
    categoryName: 'Personal Care',
    images: [],
    localImage: require('../assets/product-facecure-herbal-soap.png'),
    benefits: [
      'Natural 100% herbal formulation, chemical-free',
      'Antibacterial & antiseptic shield from Neem & Tulsi',
      'Prevents acne, breakouts, and skin impurities',
      'Deep cleansing while maintaining natural hydration',
      'Gentle on skin for daily face and body wellness',
    ],
    activeIngredients: ['Aloe Vera', 'Neem Oil', 'Tulsi Extract'],
    ingredients: ['Aloe Vera Extract', 'Neem Oil (Azadirachta Indica)', 'Tulsi Extract (Ocimum Sanctum)', 'Pure Glycerin', 'Grade-1 Soap Base'],
    usage: 'Work into a rich lather with water. Apply generously to wet face and body, leave on for 1-2 minutes, then rinse thoroughly.',
    precautions: 'For external use only. Avoid direct eye contact. Rinse immediately with cold water if contact occurs.',
    packaging: '75g Bar',
    additionalInfo: 'Grade-1 TFM soap base. Free from harsh chemicals and parabens, cruelty-free.',
    isActive: true,
    isFeatured: true,
    tags: ['soap', 'facecure', 'herbal', 'personal care', 'neem', 'aloe vera', 'tulsi', 'antibacterial', 'clean skin'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-11',
    name: 'Facecure Glow Shine Cream',
    description: 'Facecure Glow Shine Cream is an intensive brightening and radiance cream formulated with Glycolic Acid, Alpha Arbutin, Kojic Acid, Niacinamide, and broad-spectrum SPF 30. Formulated for both men and women to restore natural luminescence, fade dullness, and shield against UV damage.',
    shortDescription: 'Skin brightening cream for men & women with built-in SPF 30',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-glowshine-cream.png'),
    benefits: [
      'Synergistic brightening action with Arbutin, Kojic Acid & Niacinamide',
      'Gentle cell exfoliation and smoothing with Glycolic Acid',
      'Built-in broad-spectrum SPF 30 defends against photoaging & sun spots',
      'Imparts an instant radiant glow without grease or white cast',
      'Dermatologist tested formulation suitable for men and women',
    ],
    activeIngredients: ['Glycolic Acid', 'Alpha Arbutin', 'Kojic Acid', 'Niacinamide', 'SPF 30 Sun Protection Formula'],
    ingredients: ['Glycolic Acid', 'Alpha Arbutin', 'Kojic Acid Dipalmitate', 'Niacinamide (Vitamin B3)', 'SPF 30 UV Filters', 'Vitamin E Acetate', 'Hyaluronic Acid', 'Light Cream Base'],
    usage: 'Apply a pea-sized amount evenly over cleansed face and neck in the morning. Gently massage until fully absorbed.',
    precautions: 'For external use only. Conduct a patch test on forearm before first application. Avoid direct contact with eyes.',
    packaging: '20g Jar',
    additionalInfo: 'Non-comedogenic, dermatologically tested, suited for daily morning regimen.',
    isActive: true,
    isFeatured: true,
    tags: ['glow', 'shine', 'cream', 'facecure', 'skincare', 'brightening', 'kojic acid', 'niacinamide', 'spf30'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-12',
    name: 'Facecure Facewash',
    description: 'Facecure Facewash is a purifying herbal anti-acne face wash powered by pure Neem, Aloe Vera, Tea Tree Oil, and Tulsi extract. Formulated for all skin types, it delivers deep pore cleansing, reduces pimples, washes away excess oil, and leaves skin revitalized and clear.',
    shortDescription: 'Deep cleansing herbal facewash with Neem, Aloe Vera & Tea Tree Oil',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-facecure-facewash.png'),
    benefits: [
      'Helps visibly reduce acne and pimples within 15 days',
      'Deeply cleanses congested pores and extracts surface pollutants',
      'Antibacterial protection with pure Tea Tree Oil & Neem',
      'Soothes skin inflammation with Aloe Vera and Tulsi',
      '100% herbal active ingredients, safe for all skin types',
    ],
    activeIngredients: ['Neem', 'Aloe Vera', 'Tea Tree Oil', 'Tulsi Extract'],
    ingredients: ['Neem Extract (Azadirachta Indica)', 'Aloe Vera Barbadensis Gel', 'Tea Tree Oil (Melaleuca Alternifolia)', 'Tulsi Extract (Ocimum Sanctum)', 'Purified Water Base', 'Gentle Foaming Surfactants'],
    usage: 'Wet face and neck. Squeeze a small amount of Facecure Facewash onto palms and work into a lather. Gently massage in upward circular motions, then rinse thoroughly and pat dry. Use morning and night.',
    precautions: 'For external use only. Avoid direct contact with eyes. If contact occurs, rinse immediately with clean water.',
    packaging: '100ml Tube',
    additionalInfo: '100% herbal actives. Dermatologically tested. Non-drying deep cleansing formula.',
    isActive: true,
    isFeatured: true,
    tags: ['facewash', 'facecure', 'skincare', 'neem', 'tea tree oil', 'aloe vera', 'tulsi', 'acne', 'cleanser'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-13',
    name: 'Facecure Advance Gel',
    description: 'Facecure Advance Gel (Clindamycin & Nicotinamide Gel) is a targeted dermatological anti-acne medication. Combining antibacterial Clindamycin with anti-inflammatory Nicotinamide, it eradicates acne-causing bacteria, calms swelling and redness, and accelerates blemish healing.',
    shortDescription: 'Targeted anti-acne gel with Clindamycin & Nicotinamide',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/product-facecure-advance-gel.png'),
    benefits: [
      'Directly eliminates acne-causing bacteria (P. acnes)',
      'Relieves inflammatory acne lesions, swelling, and redness',
      'Regulates excess sebum production and prevents new comedones',
      'Fast-absorbing aqueous gel base that leaves no oily residue',
      'Dermatologist trusted formulation for clear, healthy skin',
    ],
    activeIngredients: ['Clindamycin Phosphate IP 1.0% w/w', 'Nicotinamide IP 4.0% w/w'],
    ingredients: ['Clindamycin Phosphate IP 1.0% w/w', 'Nicotinamide IP 4.0% w/w', 'Aqueous Gel Base q.s.'],
    usage: 'Cleanse the affected area with a gentle cleanser and pat dry. Apply a thin film of Facecure Advance Gel once or twice daily or as directed by your physician.',
    precautions: 'For external dermatological use only. Avoid contact with eyes, eyelids, mouth, and mucous membranes. Discontinue if extreme dryness or irritation develops.',
    packaging: '20g Tube',
    additionalInfo: 'Pharmaceutical grade topical formulation. Manufactured under certified GMP standards.',
    isActive: true,
    isFeatured: true,
    tags: ['gel', 'facecure', 'cream', 'skincare', 'clindamycin', 'nicotinamide', 'acne', 'advance gel'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-14',
    name: 'Facecure Skin Radiance Combo',
    description: 'Facecure Skin Radiance Combo is a comprehensive daily skincare synergy pairing Facecure Herbal Soap (Aloe Vera, Neem & Tulsi) and Facecure Glow Shine Cream (SPF 30, Glycolic Acid, Arbutin & Niacinamide). Purify, nourish, and shield your skin for all-day luminous glow.',
    shortDescription: 'Daily glow pack: Facecure Herbal Soap + Glow Shine Cream SPF 30',
    categoryId: 'cat-1',
    categoryName: 'Skincare',
    images: [],
    localImage: require('../assets/promo-enhance-skin.png'),
    benefits: [
      'Complete 2-step daily routine: cleanse and brighten',
      'Deep purification with natural Neem, Aloe Vera & Tulsi',
      'Targeted skin radiance with Glycolic Acid, Arbutin & Kojic Acid',
      'Broad-spectrum SPF 30 UV defense for daytime protection',
      'Specially bundled value combo for men and women',
    ],
    activeIngredients: ['Aloe Vera', 'Neem', 'Tulsi', 'Glycolic Acid', 'Arbutin', 'Kojic Acid', 'Niacinamide', 'SPF 30'],
    ingredients: ['Facecure Herbal Soap (75g)', 'Facecure Glow Shine Cream (20g)'],
    usage: 'Step 1: Cleanse face and neck with Facecure Herbal Soap and rinse with water. Step 2: Apply Facecure Glow Shine Cream evenly every morning.',
    precautions: 'For external use only. Patch test recommended before first use.',
    packaging: 'Combo Pack (Soap 75g + Cream 20g)',
    additionalInfo: 'Complete dual-action skin enhancement regimen.',
    isActive: true,
    isFeatured: true,
    tags: ['combo', 'kit', 'facecure', 'skincare', 'glow', 'soap', 'cream', 'spf30', 'radiance'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
